org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m
org.gradle.parallel=true
android.useAndroidX=true
android.enableJetifier=true
myCompileSdk=36
myMinSdk=24
myTargetSdk=36
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
